# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181112_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='client_ip',
            field=models.GenericIPAddressField(default='0000.0000.0000.0000'),
        ),
    ]
